# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20160606_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeds',
            name='product_item',
        ),
    ]
