# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 11:16
from __future__ import unicode_literals

import core.base_models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
                'db_table': 'bn_category',
                'verbose_name_plural': 'Interests Category',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
                'db_table': 'bn_language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('device_id', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('image_url', models.FileField(blank=True, max_length=200, null=True, upload_to=core.base_models.set_user_pic_path)),
                ('gender', models.CharField(blank=True, choices=[(b'M', b'Male'), (b'F', b'Female'), (b'X', b'Other')], max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='core_users', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('interests_category', models.ManyToManyField(to='core.Category')),
                ('user_languages', models.ManyToManyField(to='core.Language')),
            ],
            options={
                'abstract': False,
                'db_table': 'bn_userprofile',
                'verbose_name_plural': 'User Profile',
            },
        ),
    ]
