# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='image_url',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=b'languages-images'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=b'category-images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='device_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image_url',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=b'user-images'),
        ),
    ]
