# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160602_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='_image_url',
            new_name='image_url',
        ),
    ]
