# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
                'db_table': 'bn_news',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'News Interests Category',
            },
        ),
        migrations.CreateModel(
            name='NewsLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'News Languages',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NewsLanguage'),
        ),
        migrations.AddField(
            model_name='news',
            name='new_tags',
            field=models.ManyToManyField(to='news.NewsCategory'),
        ),
    ]
