# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newscategory_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslanguage',
            name='image_url',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=b'languages-images'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='image_url',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=b'category-images'),
        ),
    ]
