# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20160602_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='news',
            name='pubdate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
