# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20160603_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='language',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_tags',
        ),
    ]
