# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20160603_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.NewsCategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.NewsLanguage'),
        ),
    ]
