# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20160603_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pubdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
