# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20160606_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
