# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20160606_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
